name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Create api .env file
        run: cd apps/api && echo "${{secrets.API_ENV_PRODUCTION}}" > .env

      - name: Create web .env file
        run: cd apps/web && echo "${{secrets.WEB_ENV_PRODUCTION}}" > .env

      - name: Install dependencies
        run: pnpm install

      - name: Prisma generate
        run: cd apps/api && npx prisma generate

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/restaurant_management
            git fetch --all
            git reset --hard origin/main
            cd apps/api && echo "${{secrets.API_ENV_PRODUCTION}}" > .env
            cd ../..
            cd apps/web && echo "${{secrets.WEB_ENV_PRODUCTION}}" > .env
            cd ../..
            pnpm install
            cd apps/api && npx prisma generate
            pnpm build
            pm2 restart restaurant-management
